function cfg = run_021
%RUN_021  Auto-generated by generate_sweep — do not edit.
%   Sweep: 002_organ_lr  |  Run 21 of 64
%   lr=0.0003  epochs=50  batch_size=32  seed=42  use_batch_norm=true

    cfg = organmnist3d();

    cfg.lr               = 0.0003;
    cfg.epochs           = 50;
    cfg.batchSize        = 32;
    cfg.seed             = 42;
    cfg.useBatchNorm     = true;
end
