function cfg = run_042
%RUN_042  Auto-generated by generate_sweep — do not edit.
%   Sweep: 002_organ_lr  |  Run 42 of 64
%   lr=0.0005  epochs=100  batch_size=16  seed=42  use_batch_norm=false

    cfg = organmnist3d();

    cfg.lr               = 0.0005;
    cfg.epochs           = 100;
    cfg.batchSize        = 16;
    cfg.seed             = 42;
    cfg.useBatchNorm     = false;
end
