function cfg = run_046
%RUN_046  Auto-generated by generate_sweep — do not edit.
%   Sweep: 002_organ_lr  |  Run 46 of 64
%   lr=0.0005  epochs=100  batch_size=32  seed=42  use_batch_norm=false

    cfg = organmnist3d();

    cfg.lr               = 0.0005;
    cfg.epochs           = 100;
    cfg.batchSize        = 32;
    cfg.seed             = 42;
    cfg.useBatchNorm     = false;
end
