function cfg = run_005
%RUN_005  Auto-generated by generate_sweep — do not edit.
%   Sweep: 002_organ_lr  |  Run 5 of 64
%   lr=0.0001  epochs=50  batch_size=32  seed=42  use_batch_norm=true

    cfg = organmnist3d();

    cfg.lr               = 0.0001;
    cfg.epochs           = 50;
    cfg.batchSize        = 32;
    cfg.seed             = 42;
    cfg.useBatchNorm     = true;
end
