function cfg = run_012
%RUN_012  Auto-generated by generate_sweep — do not edit.
%   Sweep: 002_organ_lr  |  Run 12 of 64
%   lr=0.0001  epochs=100  batch_size=16  seed=1337  use_batch_norm=false

    cfg = organmnist3d();

    cfg.lr               = 0.0001;
    cfg.epochs           = 100;
    cfg.batchSize        = 16;
    cfg.seed             = 1337;
    cfg.useBatchNorm     = false;
end
