function cfg = run_020
%RUN_020  Auto-generated by generate_sweep — do not edit.
%   Sweep: 002_organ_lr  |  Run 20 of 64
%   lr=0.0003  epochs=50  batch_size=16  seed=1337  use_batch_norm=false

    cfg = organmnist3d();

    cfg.lr               = 0.0003;
    cfg.epochs           = 50;
    cfg.batchSize        = 16;
    cfg.seed             = 1337;
    cfg.useBatchNorm     = false;
end
