function cfg = run_023
%RUN_023  Auto-generated by generate_sweep — do not edit.
%   Sweep: 002_organ_lr  |  Run 23 of 64
%   lr=0.0003  epochs=50  batch_size=32  seed=1337  use_batch_norm=true

    cfg = organmnist3d();

    cfg.lr               = 0.0003;
    cfg.epochs           = 50;
    cfg.batchSize        = 32;
    cfg.seed             = 1337;
    cfg.useBatchNorm     = true;
end
