function cfg = run_057
%RUN_057  Auto-generated by generate_sweep — do not edit.
%   Sweep: 002_organ_lr  |  Run 57 of 64
%   lr=0.001  epochs=100  batch_size=16  seed=42  use_batch_norm=true

    cfg = organmnist3d();

    cfg.lr               = 0.001;
    cfg.epochs           = 100;
    cfg.batchSize        = 16;
    cfg.seed             = 42;
    cfg.useBatchNorm     = true;
end
