function cfg = run_003
%RUN_003  Auto-generated by generate_sweep — do not edit.
%   Sweep: 002_organ_lr  |  Run 3 of 64
%   lr=0.0001  epochs=50  batch_size=16  seed=1337  use_batch_norm=true

    cfg = organmnist3d();

    cfg.lr               = 0.0001;
    cfg.epochs           = 50;
    cfg.batchSize        = 16;
    cfg.seed             = 1337;
    cfg.useBatchNorm     = true;
end
