function cfg = run_036
%RUN_036  Auto-generated by generate_sweep — do not edit.
%   Sweep: 002_organ_lr  |  Run 36 of 64
%   lr=0.0005  epochs=50  batch_size=16  seed=1337  use_batch_norm=false

    cfg = organmnist3d();

    cfg.lr               = 0.0005;
    cfg.epochs           = 50;
    cfg.batchSize        = 16;
    cfg.seed             = 1337;
    cfg.useBatchNorm     = false;
end
