function cfg = run_034
%RUN_034  Auto-generated by generate_sweep — do not edit.
%   Sweep: 002_organ_lr  |  Run 34 of 64
%   lr=0.0005  epochs=50  batch_size=16  seed=42  use_batch_norm=false

    cfg = organmnist3d();

    cfg.lr               = 0.0005;
    cfg.epochs           = 50;
    cfg.batchSize        = 16;
    cfg.seed             = 42;
    cfg.useBatchNorm     = false;
end
