function cfg = run_035
%RUN_035  Auto-generated by generate_sweep — do not edit.
%   Sweep: 002_organ_lr  |  Run 35 of 64
%   lr=0.0005  epochs=50  batch_size=16  seed=1337  use_batch_norm=true

    cfg = organmnist3d();

    cfg.lr               = 0.0005;
    cfg.epochs           = 50;
    cfg.batchSize        = 16;
    cfg.seed             = 1337;
    cfg.useBatchNorm     = true;
end
