function cfg = run_016
%RUN_016  Auto-generated by generate_sweep — do not edit.
%   Sweep: 005_fracture_lr  |  Run 16 of 16
%   lr=0.001  use_batch_norm=false  seed=1337

    cfg = fracturemnist3d();

    cfg.lr               = 0.001;
    cfg.useBatchNorm     = false;
    cfg.seed             = 1337;
end
