function cfg = run_009
%RUN_009  Auto-generated by generate_sweep — do not edit.
%   Sweep: 005_fracture_lr  |  Run 9 of 16
%   lr=0.0005  use_batch_norm=true  seed=42

    cfg = fracturemnist3d();

    cfg.lr               = 0.0005;
    cfg.useBatchNorm     = true;
    cfg.seed             = 42;
end
