function cfg = run_008
%RUN_008  Auto-generated by generate_sweep — do not edit.
%   Sweep: 005_fracture_lr  |  Run 8 of 16
%   lr=0.0003  use_batch_norm=false  seed=1337

    cfg = fracturemnist3d();

    cfg.lr               = 0.0003;
    cfg.useBatchNorm     = false;
    cfg.seed             = 1337;
end
