function cfg = run_001
%RUN_001  Auto-generated by generate_sweep — do not edit.
%   Sweep: 005_fracture_lr  |  Run 1 of 16
%   lr=0.0001  use_batch_norm=true  seed=42

    cfg = fracturemnist3d();

    cfg.lr               = 0.0001;
    cfg.useBatchNorm     = true;
    cfg.seed             = 42;
end
