function cfg = run_002
%RUN_002  Auto-generated by generate_sweep — do not edit.
%   Sweep: 006_synapse_lr  |  Run 2 of 16
%   lr=0.0001  use_batch_norm=true  seed=1337

    cfg = synapsemnist3d();

    cfg.lr               = 0.0001;
    cfg.useBatchNorm     = true;
    cfg.seed             = 1337;
end
