function cfg = run_010
%RUN_010  Auto-generated by generate_sweep — do not edit.
%   Sweep: 006_synapse_lr  |  Run 10 of 16
%   lr=0.0005  use_batch_norm=true  seed=1337

    cfg = synapsemnist3d();

    cfg.lr               = 0.0005;
    cfg.useBatchNorm     = true;
    cfg.seed             = 1337;
end
