function cfg = run_003
%RUN_003  Auto-generated by generate_sweep — do not edit.
%   Sweep: 006_synapse_lr  |  Run 3 of 16
%   lr=0.0001  use_batch_norm=false  seed=42

    cfg = synapsemnist3d();

    cfg.lr               = 0.0001;
    cfg.useBatchNorm     = false;
    cfg.seed             = 42;
end
