function cfg = run_004
%RUN_004  Auto-generated by generate_sweep — do not edit.
%   Sweep: 003_adrenal_lr  |  Run 4 of 16
%   lr=0.0001  use_batch_norm=false  seed=1337

    cfg = adrenalmnist3d();

    cfg.lr               = 0.0001;
    cfg.useBatchNorm     = false;
    cfg.seed             = 1337;
end
