function cfg = run_013
%RUN_013  Auto-generated by generate_sweep — do not edit.
%   Sweep: 003_adrenal_lr  |  Run 13 of 16
%   lr=0.001  use_batch_norm=true  seed=42

    cfg = adrenalmnist3d();

    cfg.lr               = 0.001;
    cfg.useBatchNorm     = true;
    cfg.seed             = 42;
end
