function cfg = run_012
%RUN_012  Auto-generated by generate_sweep — do not edit.
%   Sweep: 003_adrenal_lr  |  Run 12 of 16
%   lr=0.0005  use_batch_norm=false  seed=1337

    cfg = adrenalmnist3d();

    cfg.lr               = 0.0005;
    cfg.useBatchNorm     = false;
    cfg.seed             = 1337;
end
