function cfg = run_015
%RUN_015  Auto-generated by generate_sweep — do not edit.
%   Sweep: 003_adrenal_lr  |  Run 15 of 16
%   lr=0.001  use_batch_norm=false  seed=42

    cfg = adrenalmnist3d();

    cfg.lr               = 0.001;
    cfg.useBatchNorm     = false;
    cfg.seed             = 42;
end
