function cfg = run_005
%RUN_005  Auto-generated by generate_sweep — do not edit.
%   Sweep: 004_vessel_lr  |  Run 5 of 16
%   lr=0.0003  use_batch_norm=true  seed=42

    cfg = vesselmnist3d();

    cfg.lr               = 0.0003;
    cfg.useBatchNorm     = true;
    cfg.seed             = 42;
end
