function cfg = run_007
%RUN_007  Auto-generated by generate_sweep — do not edit.
%   Sweep: 004_vessel_lr  |  Run 7 of 16
%   lr=0.0003  use_batch_norm=false  seed=42

    cfg = vesselmnist3d();

    cfg.lr               = 0.0003;
    cfg.useBatchNorm     = false;
    cfg.seed             = 42;
end
