function cfg = run_011
%RUN_011  Auto-generated by generate_sweep — do not edit.
%   Sweep: 004_vessel_lr  |  Run 11 of 16
%   lr=0.0005  use_batch_norm=false  seed=42

    cfg = vesselmnist3d();

    cfg.lr               = 0.0005;
    cfg.useBatchNorm     = false;
    cfg.seed             = 42;
end
