function cfg = run_014
%RUN_014  Auto-generated by generate_sweep — do not edit.
%   Sweep: 004_vessel_lr  |  Run 14 of 16
%   lr=0.001  use_batch_norm=true  seed=1337

    cfg = vesselmnist3d();

    cfg.lr               = 0.001;
    cfg.useBatchNorm     = true;
    cfg.seed             = 1337;
end
