function cfg = run_006
%RUN_006  Auto-generated by generate_sweep — do not edit.
%   Sweep: 004_vessel_lr  |  Run 6 of 16
%   lr=0.0003  use_batch_norm=true  seed=1337

    cfg = vesselmnist3d();

    cfg.lr               = 0.0003;
    cfg.useBatchNorm     = true;
    cfg.seed             = 1337;
end
