function cfg = run_004
%RUN_004  Auto-generated by generate_sweep — do not edit.
%   Sweep: 001_nodule_smoke  |  Run 4 of 4
%   lr=0.0003  seed=1337

    cfg = nodulemnist3d();

    cfg.lr               = 0.0003;
    cfg.seed             = 1337;
end
