function cfg = run_002
%RUN_002  Auto-generated by generate_sweep — do not edit.
%   Sweep: 001_nodule_smoke  |  Run 2 of 4
%   lr=0.0001  seed=1337

    cfg = nodulemnist3d();

    cfg.lr               = 0.0001;
    cfg.seed             = 1337;
end
