function opts = buildTrainingOptions(cfg, valDs, itersPerEpoch)
%BUILDTRAININGOPTIONS Build trainingOptions for trainnet.
%
%   opts = buildTrainingOptions(cfg, valDs, itersPerEpoch)
%
%   Validates once per epoch (ValidationFrequency = itersPerEpoch).
%   Returns the network snapshot with the best validation loss.

    arguments
        cfg           (1,1) struct
        valDs               % datastore — no type constraint (MATLAB ds hierarchy)
        itersPerEpoch (1,1) double {mustBePositive, mustBeInteger}
    end

    opts = trainingOptions(cfg.optimizer, ...
        'InitialLearnRate',    cfg.lr, ...
        'MaxEpochs',           cfg.epochs, ...
        'MiniBatchSize',       cfg.batchSize, ...
        'Shuffle',             'every-epoch', ...
        'ValidationData',      valDs, ...
        'ValidationFrequency', itersPerEpoch, ...
        'OutputNetwork',       'best-validation-loss', ...
        'Plots',               'none', ...
        'Verbose',             true, ...
        'VerboseFrequency',    itersPerEpoch);
end
